### Start test files for Docker-DocumentServer
run-name: "Scheduled tests Docker-DocumentServer"

on:
  push:
  pull_request:
    types: [opened, reopened, synchronize]
    paths-ignore:
      - '.github/**'
      - 'tests/**'
      - '**/README.md'

jobs:
  start_test_files:
    name: "File: ${{ matrix.name }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - compose_file: postgres.yml
            variables: "POSTGRES_VERSION=9.5"                           # postgtres 9.5 version
            name: "Test with Postgresql 9.5"


    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: "Start ${{ matrix.name }}"
        run: |
          cd tests                                                    
          export config=${{ matrix.compose_file }}                    # Export .yml files in variable config
          echo "export variables for ${{ matrix.compose_file }}"       
          for v in ${{ matrix.variables }}; do
            export ${v}
          done
          ./test.sh
